all:
  children:
    cloud:
      hosts:
        cloud1:
          ansible_connection: local
          skupper_option_kubeconfig: "{{ lookup('ansible.builtin.env', 'HOME') }}/.kube/config"
          skupper_option_namespace: nearestprime-1
          skupper_init_site_name: cloud-1
          skupper_init_enable_service_sync: 'false'
          skupper_token_type: cert
          skupper_service_list:
            - name: nearestprime
              ports:
                - 8000
              targets:
                - type: deployment
                  name: nearestprime
            - name: db
              ports:
                - 5432
    onprem:
      hosts:
        rhel9:
          ansible_connection: local # comment if running against a remote (ssh) machine
          # uncomment below if deploying to a remote machine
          #ansible_host: <remote_ip_addr> # it expects that your user is able to ssh into this IP using its own ssh keys
          skupper_option_platform: podman
          skupper_init_site_name: onprem-1
          skupper_init_container_network: nearestprime
          skupper_link_list:
            - host: cloud1
          skupper_service_list:
            - name: db
              ports: [5432]
              targets:
                - type: "host"
                  name: "db-container"
              host_ports:
                - 5432:5432
            - name: load-gen
              ports: [8080]
              targets:
                - type: "host"
                  name: "load-gen-container"
              host_ports:
                - 8080:8080
            - name: nearestprime
              ports:
                - 8000
