---
- hosts: onprem
  collections:
    - containers.podman
  tasks:
    - name: "Starting load generator"
      ansible.builtin.uri:
        url: "http://0.0.0.0:8080/set_load/{{ load_gen_size | default(1) }}"
      
