---
- hosts: cloud
  collections:
    - kubernetes.core
  tasks:
  - ansible.builtin.include_tasks: setup-k8s.yml
- hosts: onprem
  collections:
    - containers.podman
    - skupper.skupper
  tasks:
  - ansible.builtin.include_tasks: setup-podman.yml
- hosts: all
  collections:
    - skupper.skupper
  tasks:
  - ansible.builtin.include_tasks: setup-skupper.yml
