---
- name: Deleting the namespace
  kubernetes.core.k8s:
    name: "{{ skupper_option_namespace }}"
    api_version: v1
    kind: Namespace
    state: absent
    kubeconfig: "{{ skupper_option_kubeconfig }}"
