---
- hosts: all
  collections:
    - skupper.skupper
  tasks:
  - ansible.builtin.include_tasks: teardown-skupper.yml
- hosts: cloud
  collections:
    - kubernetes.core
  tasks:
  - ansible.builtin.include_tasks: teardown-k8s.yml
- hosts: onprem
  collections:
    - containers.podman
  tasks:
  - ansible.builtin.include_tasks: teardown-podman.yml
